<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>DataVanger.Engine</AssemblyName>
    <RootNamespace>DataVanger.Engine</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataVanger.Shared\DataVanger.Shared.csproj" />
  </ItemGroup>
</Project>
