using System;

namespace DataVanger.Shared.Behavioral.Runtime;

/// <summary>
/// Immutable health/status snapshot of the Behavioral Engine Runtime
/// Binding. Cheap to produce, never throws, safe to surface in UI later.
///
/// Anti-FP note: none of these counters are verdicts. EvidenceGenerated
/// counts behavioral evidence items, which are evidence only.
/// </summary>
public sealed class BehavioralRuntimeBindingStatus
{
    public bool Enabled { get; init; }
    public bool PassiveMode { get; init; }
    public bool DevelopmentMode { get; init; }

    public BehavioralRuntimeBindingState State { get; init; } = BehavioralRuntimeBindingState.Disabled;

    /// <summary>Total runtime events received by the binding consumer.</summary>
    public long EventsReceived { get; init; }

    /// <summary>Total behavioral observations created by the adapter.</summary>
    public long ObservationsCreated { get; init; }

    /// <summary>Total behavioral evidence items generated by the rules.</summary>
    public long EvidenceGenerated { get; init; }

    /// <summary>
    /// Total events/observations dropped (disabled, rate-limited, or
    /// shed under state pressure). Bounded by design — the binding never
    /// grows memory without bound.
    /// </summary>
    public long EventsDropped { get; init; }

    /// <summary>Number of processes currently tracked in correlation state.</summary>
    public int TrackedProcesses { get; init; }

    public string? LastWarning { get; init; }

    public DateTimeOffset? LastEventUtc { get; init; }
}
